version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:8.16.1
jobs:
  prepare-deps:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install dependencies
          command: npm ci
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  test:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run tests
          command: npm test
workflows:
  version: 2
  build_and_test:
    jobs:
      - prepare-deps
      - test:
          requires:
            - prepare-deps
